# Generated by Django 4.0.2 on 2022-03-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(blank=True, max_length=50, null=True)),
                ('author', models.EmailField(blank=True, max_length=50, null=True)),
                ('dop', models.DateField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('condition', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
