# Generated by Django 4.0.3 on 2022-03-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_remove_book_fk_user_book_hk_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_master',
            name='created_date',
            field=models.DateField(blank=True, max_length=50, null=True),
        ),
    ]
