# Generated by Django 4.0.3 on 2022-03-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0007_remove_book_master_created_date_book_master_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_master',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
