# Generated by Django 4.0.3 on 2022-03-14 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0008_book_master_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_master',
            name='date',
        ),
        migrations.RemoveField(
            model_name='book_master',
            name='month',
        ),
    ]
