# Generated by Django 4.0.3 on 2022-03-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0011_remove_book_master_date_remove_book_master_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_master',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
