# Generated by Django 4.0.3 on 2022-03-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0016_book_master_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='designation',
            new_name='condition',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='doj',
            new_name='issue_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='fk_user',
        ),
        migrations.AddField(
            model_name='student',
            name='img',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='student',
            name='request_generator',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
