# Generated by Django 4.0.3 on 2022-03-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0017_rename_designation_student_condition_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='issue_date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='student',
            name='start_date',
            field=models.DateField(blank=True, max_length=50, null=True),
        ),
    ]
