# Generated by Django 4.0.3 on 2022-03-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0020_rename_end_date_student_issue_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stu_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
