# Generated by Django 4.0.3 on 2022-03-16 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0021_student_stu_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='stu_name',
        ),
    ]
