# Generated by Django 4.0.3 on 2022-03-17 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0022_rename_name_student_stu_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('designation', models.CharField(max_length=50)),
                ('doj', models.DateField(max_length=50)),
                ('hk_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='library_app.user')),
            ],
        ),
    ]
