# Generated by Django 4.0.3 on 2022-03-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0024_alter_employee_designation_alter_employee_doj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='img',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to='Student_Images/'),
        ),
    ]
