# Generated by Django 4.0.3 on 2022-03-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0025_alter_student_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='request',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
