# Generated by Django 4.0.3 on 2022-03-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0026_student_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='request',
            field=models.BooleanField(blank=True, max_length=50, null=True),
        ),
    ]
