# Generated by Django 4.0.3 on 2022-03-21 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0027_alter_student_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='request',
            new_name='status',
        ),
    ]
