# Generated by Django 4.0.3 on 2022-03-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0028_rename_request_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
