# Generated by Django 4.0.3 on 2022-03-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0030_rename_status_student_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
