# Generated by Django 4.0.3 on 2022-03-24 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0034_remove_new_category_rent_rent_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent_category',
            old_name='hk_user',
            new_name='hk_rent',
        ),
    ]
