# Generated by Django 4.0.3 on 2022-03-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0035_rename_hk_user_rent_category_hk_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='difference',
            field=models.DateField(blank=True, null=True),
        ),
    ]
