# Generated by Django 4.0.3 on 2022-03-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0039_alter_student_difference'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='charges',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
