# Generated by Django 4.0.3 on 2022-03-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0044_alter_student_return_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='payment_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
