# Generated by Django 4.0.3 on 2022-03-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0045_student_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(blank=True, max_length=50, null=True)),
                ('visitor_plan', models.CharField(blank=True, max_length=50, null=True)),
                ('book_name', models.CharField(blank=True, max_length=50, null=True)),
                ('visit_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('contact_No', models.IntegerField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
