# Generated by Django 4.0.3 on 2022-03-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0046_daily_visitors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_visitors',
            name='contact_No',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
