# Generated by Django 4.0.3 on 2022-03-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0048_rent_category_hourly_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_visitors',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='daily_visitors',
            name='visit_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
