# Generated by Django 4.0.3 on 2022-03-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0049_alter_daily_visitors_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_visitors',
            name='accept_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='daily_visitors',
            name='payment_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
