# Generated by Django 4.0.3 on 2022-03-28 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0050_daily_visitors_accept_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daily_visitors',
            old_name='payment_status',
            new_name='payment_status_time',
        ),
    ]
