# Generated by Django 4.0.3 on 2022-03-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0052_daily_visitors_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furniture', models.CharField(blank=True, max_length=100, null=True)),
                ('electronics', models.CharField(blank=True, max_length=100, null=True)),
                ('fur_dop', models.DateField(blank=True, max_length=100, null=True)),
                ('Pur_price', models.CharField(blank=True, max_length=100, null=True)),
                ('condition', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
