# Generated by Django 4.0.3 on 2022-03-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0054_remove_furniture_master_pur_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture_master',
            name='Pur_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='furniture_master',
            name='condition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='furniture_master',
            name='electronics',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='furniture_master',
            name='fur_dop',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
    ]
