# Generated by Django 4.0.3 on 2022-03-30 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0055_furniture_master_pur_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furniture_master',
            name='Pur_price',
        ),
        migrations.RemoveField(
            model_name='furniture_master',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='furniture_master',
            name='electronics',
        ),
        migrations.RemoveField(
            model_name='furniture_master',
            name='fur_dop',
        ),
        migrations.CreateModel(
            name='Furniture_Duplicate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electronics', models.CharField(blank=True, max_length=100, null=True)),
                ('fur_dop', models.DateField(blank=True, max_length=100, null=True)),
                ('Pur_price', models.CharField(blank=True, max_length=100, null=True)),
                ('condition', models.CharField(blank=True, max_length=100, null=True)),
                ('hk_furniture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='library_app.furniture_master')),
            ],
        ),
    ]
