# Generated by Django 4.0.3 on 2022-03-31 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0056_remove_furniture_master_pur_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='designation',
            new_name='destination',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='doj',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.AddField(
            model_name='employee',
            name='monthly_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='yearly_package',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
