# Generated by Django 4.0.3 on 2022-04-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0059_bills_master_bills_duplicate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bills_duplicate',
            old_name='payment_type',
            new_name='paid_status',
        ),
        migrations.RenameField(
            model_name='bills_duplicate',
            old_name='status',
            new_name='payment_status',
        ),
        migrations.AddField(
            model_name='bills_duplicate',
            name='amount',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='bills_duplicate',
            name='month',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bills_duplicate',
            name='payment_date',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
    ]
