# Generated by Django 4.0.3 on 2022-04-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0060_rename_payment_type_bills_duplicate_paid_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills_duplicate',
            name='online_var',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
