# Generated by Django 4.0.3 on 2022-04-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0062_alter_bills_duplicate_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills_duplicate',
            name='paid_status',
            field=models.BooleanField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bills_duplicate',
            name='payment_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
