# Generated by Django 4.0.3 on 2022-04-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0064_alter_bills_duplicate_paid_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills_duplicate',
            name='paid_status',
            field=models.CharField(blank=True, default=False, max_length=100, null=True),
        ),
    ]
