# Generated by Django 4.0.3 on 2022-05-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0065_alter_bills_duplicate_paid_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='City_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bills_duplicate',
            name='paid_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
