# Generated by Django 4.0.3 on 2022-05-31 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0066_city_master_alter_bills_duplicate_paid_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state_id', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='City_Master',
        ),
    ]
