# Generated by Django 4.1.7 on 2023-05-02 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0068_rename_name_citymaster_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills_duplicate',
            name='fk_bill_type',
        ),
        migrations.DeleteModel(
            name='CityMaster',
        ),
        migrations.RemoveField(
            model_name='furniture_duplicate',
            name='hk_furniture',
        ),
        migrations.DeleteModel(
            name='Bills_Duplicate',
        ),
        migrations.DeleteModel(
            name='Bills_Master',
        ),
        migrations.DeleteModel(
            name='Furniture_Duplicate',
        ),
        migrations.DeleteModel(
            name='Furniture_Master',
        ),
    ]
